### ISSUE TITLE
Redd Coin won't update

### ISSUE THREAD

**Issue by sutheep** [chrislennon/Crypto-Touchbar-App#69] opened 2018-01-22 05:04 UTC
Reddcoin won't update on touchbar. Shows an error.

Traceback (most recent call last):
  File "<string>", line 5, in <module>
ValueError: Unknown format code 'f' for object of type 'unicode'

**Comment by chrislennon** [comment] 2018-01-22 08:35
Confirmed, I get errors for redcoin when using either of the following options:
- Relative $ Range (-$000 / +$000) 
- Change % based on opening (+10%)
- Relative % Range (-8% / +10%)
- Relative $ Range based on user percentage (-$000 / +$000)

The others appear to work. Will investigate and push a correction today.

**Comment by sutheep** [comment] 2018-01-22 08:46
Thanks Chris for the prompt response.




Regards,
Sutheep Singhsachakul

**Comment by chrislennon** [comment] 2018-01-22 09:54
@sutheep #70 should of now fixed this - and should now be deployed, I hadn't checked the 'advanced options' fully.

Give it a test see if you can replicate it - if you run into it again just let me know which coin and which settings (or a copy of the script) 😄

**Comment by sutheep** [comment] 2018-01-23 06:25
Hi Chris,
  It’s still happening.
It’s REDDCOIN (RDD).

Also happening to a lot of alt coins.

Script:
import urllib2,json,sys

data = urllib2.urlopen("
https://min-api.cryptocompare.com/data/pricemultifull?fsyms=RDD&tsyms=USD")
obj=json.load(data)
current = "{:0,}".format(obj["RAW"]["RDD"]["USD"]["PRICE"])
opening = obj["RAW"]["RDD"]["USD"]["OPEN24HOUR"]
high = "{:0,}".format(obj["RAW"]["RDD"]["USD"]["HIGHDAY"])
low = "{:0,}".format(obj["RAW"]["RDD"]["USD"]["LOWDAY"])
raw_current = float(obj["RAW"]["RDD"]["USD"]["PRICE"])
raw_opening = float(obj["RAW"]["RDD"]["USD"]["OPEN24HOUR"])
raw_high = float(obj["RAW"]["RDD"]["USD"]["HIGHDAY"])
raw_low = float(obj["RAW"]["RDD"]["USD"]["LOWDAY"])

if (raw_current > raw_opening):
trend = "▲"
else:
trend = "▼"

print(“$" + current + " " + trend)

Result:

Traceback (most recent call last):

  File "<string>", line 5, in <module>

ValueError: Cannot specify ',' with 's'.



Sutheep Singhsachakul

**Comment by chrislennon** [comment] 2018-01-23 11:45
Hey, thanks for the code (by the way can use 3 ` symbols to start and stop a code block).

Thanks to your response i think i see the issue. Looks like the formatting options are causing issues for certain coins - I'm going to dig into this soon to see if i can resolve it globablly.

However for now, in your example above it looks like unticking 'Separate thousands with commas' and keeping the decimal places to infinite resolves it for now.

Will update this ticket when I have a a better fix in place.

**Closed as completed** 2018-01-24 10:24 UTC

**Comment by chrislennon** [comment] 2018-01-24 10:28
This issue has been closed as part of #76.

After moving to python away from applescript there were a few issues regarding formatting options. This PR should resolve the issues going forward, please let me know if it works and of course if the issue continues reopen this issue and we can debug further.
